### ISSUE TITLE
Add Arquillian Graphene  @InitialPage support

### ISSUE THREAD

**Issue by kostd** [cukespace/cukespace#111]
Graphene allows `@InitialPage`, `@Page`, PageFragments, interceptors etc.
We already have graphene-based uitest-framework and cannot use cuckes until it not supports graphene :'(

I tried something like this:

> 

	@Given("^open HomePage$")
	public void open_HomePage(@InitialPage HomePage page) throws Throwable {

> 

but this is not work:

> 
  Scenario: download history of last user actions # system/home/HomePageFeature.feature:4
    Given open HomePage                           # HomePageSteps.open_HomePage(HomePage)
      cucumber.runtime.CucumberException: Arity mismatch: Step Definition system.home.HomePageSteps.open_HomePage(HomePage) in file:/D:/Work/server-app/system-env-ui/target/test-classes/ with pattern [^open HomePage$] is declared with 1 parameters. However, the gherkin step has 0 arguments []. 
> 

Cuckes think that my param must be a step-param, but I think that it is InitialPage injection

**Comment by rmannibucau** [comment]
Hi @kostd , graphene is supported since the beginning but you must respect cucumber injections so probably use fields instead of parameters (not that cukespace doesnt use @Test methods with param injection but cucumber param injections instead):  https://github.com/cukespace/cukespace/blob/ca9dc5d312d6b152bbb48e319807b2be1bea3686/examples/src/test/java/cucumber/runtime/arquillian/feature/glue/CukeBellyGlue.java#L26

**Comment by rmannibucau** [comment]
You can inject N pages in a step, they are resolved contextually and lazily so it should work as well. Only initial page doesnt work but can easily be replaced by the rest of the graphene API so not a blocker.
